apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Skip applying the Tekton/PaC operands while the Tekton/PaC operator is being installed.
# See more information about this option, here: 
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types 
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - git::https://github.com/openshift-pipelines/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service?ref=42c250bbb8e153309dd7316fda74c47a470030e4
  - git::https://github.com/openshift-pipelines/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service-storage?ref=42c250bbb8e153309dd7316fda74c47a470030e4

components:
  - ../components/tekton-chains
