---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/openshift-pipelines/pipeline-service/operator/gitops/argocd/grafana/?ref=b0f4189ef54e857f733a2775a23d2b7a625639ed
