resources:
  - https://github.com/redhat-appstudio/sprayproxy/config?ref=076942559b739729c156b3d64f87efda1731ab90

namespace: sprayproxy

images:
  - name: ko://github.com/redhat-appstudio/sprayproxy
    newName: quay.io/redhat-appstudio/sprayproxy
    newTag: 076942559b739729c156b3d64f87efda1731ab90

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
